### ISSUE TITLE
Crash when right-clicking cushion

### ISSUE THREAD

**Issue by angelnc1989** [MinerArcana/Astral#124]
https://pastebin.com/r77w5CQu

**Comment by Alan19** [comment]
Fixed in 2983ea12cd1882927315dcd02aecd6f6ee548888. I'll post a version with the fix in a few days that comes with some other fixes.

**Comment by Alan19** [comment]
Version 1.9.7 and above should fix this issue. Thanks for reporting it and let me know if it's still occurring!
