### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by Thunder-Nova** [MinerArcana/Astral#134]
The Introspection medicine drops a body on the floor, and will spew out some random items from the inventory at the same time. The user returns with the dupe on the floor.

![](https://cdn.discordapp.com/attachments/865762410098327572/868371646237532201/unknown.png)

**Comment by Alan19** [comment]
What version of Astral are you using, and how did you get back to the overworld after you've used Introspection Medicine?

**Comment by Thunder-Nova** [comment]
The pack uses 1.9.16, hub says he used the keyhole to get back.

But the dupe only needs at least the use of the medicine so that the items pops out of the body.

**Comment by Alan19** [comment]
Usually the body disappears without the items getting dropped, I'll investigate when I get time

**Comment by Thunder-Nova** [comment]
The body does disappear when he returns (my in-game names is Thunder_Nova and Pun_isher)

**Comment by Alan19** [comment]
It seems like if you try to leave the inner realm by teleporting out of the dimension with commands, waystones, etc., the next time you lose Astral Travel you start duping the items in your inner realm inventory

**Comment by Alan19** [comment]
The fix for this issue will be released in version 1.9.17. Please reopen the issue if you are still experiencing this bug.
