### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by EleC0TroN** [MinerArcana/Astral#49]
[ru_ru.json.txt](https://github.com/MinerArcana/Astral/files/4050688/ru_ru.json.txt)
(Json files are not supported in there)

**Comment by Alan19** [comment]
I made a branch for the Russian translation. In the future, you should be able to open a pull request to edit or create a file by going to the webpage for the folder with the file you want to edit or create and then dragging the file from your computer to the page.

https://github.com/MinerArcana/Astral/blob/russian-translation/src/main/resources/assets/astral/lang/ru_ru.json

**Comment by Alan19** [comment]
Do you want the branch to be merged or would you like to make some edits?

**Comment by EleC0TroN** [comment]
![chorus_flower](https://user-images.githubusercontent.com/35199902/72226731-4c0cba80-35a5-11ea-96c5-a834b0358b38.png)

I tried to do this

**Comment by Alan19** [comment]
Huh. Probably need to fork it then.

**Comment by Alan19** [comment]
Anyways, it's been merged. Thanks!
