### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by tommyjcode** [MinerArcana/Astral#55]
I'm trying to play with my cousins, astral-0.6.5.jar doesn't seem to like servers. Here's the report:
[https://paste.ubuntu.com/p/bwhJTzfbyz/](https://paste.ubuntu.com/p/bwhJTzfbyz/)

**Comment by Alan19** [comment]
Do you have the entire log for when you launched the server?

**Comment by ghost** [comment]
Hey, sorry. Yes I do. It's been pretty hectic for me lately and I must have missed your notification. I'll see if the 1.0.0 fixes it, and if not, I'll send a report.

**Comment by Alan19** [comment]
I've identified the bug. Trying to release a working version soon.

**Comment by Alan19** [comment]
Should be resolved through:
https://github.com/MinerArcana/Astral/commit/08ad0174bbedf34accfb70e0794f5c5ea3d0ca29
https://github.com/MinerArcana/Astral/commit/52634064d13ea4596c34e317fa9d2ca6646bc01d
https://github.com/MinerArcana/Astral/commit/88464eb46f2b5dfbf9945d037922e008ffba7488

Please re-open if you're still having issues with version 1.0.3.
