### ISSUE TITLE
Game crashed when tried to use the introspective medicine.

### ISSUE THREAD

**Issue by ShadoUchiha** [MinerArcana/Astral#66]
[crash-2020-05-06_13.56.18-server.txt](https://github.com/MinerArcana/Astral/files/4585645/crash-2020-05-06_13.56.18-server.txt)

**Comment by Alan19** [comment]
I'm unable to reproduce the issue. Does it crash every time you use introspective medicine? 
Also, I would appreciate it if you can upload the crash report to pastebin next time.

**Comment by ShadoUchiha** [comment]
Yes, it crashes every time I use the medicine. I'll try to check if creating a new world solves the problem and if it doesn't, I'll upload the crash report to pastebin. Btw I'll also let you know if that solves the problem.

**Comment by drizzs** [comment]
Can you provide a bit more information, Are you using a server or are you playing single player?

**Comment by ShadoUchiha** [comment]
I'm playing single player.

**Comment by ShadoUchiha** [comment]
Well, creating a new world solves this problem somewhat but it still crashed after I tried it the third time.

**Comment by drizzs** [comment]
Basically, Alan is creating the world during the dimension registry event, Basically the dimension isn't created and because of how he associates the teleport to the dimension type it returns a null pointer. There are a few things he can do. I'm sure he'll get to it! Thanks for the info Shado. We were however unable to reproduce the issue on our end.

**Comment by ShadoUchiha** [comment]
Thank you for your help Alan and Drizzs.

**Comment by Alan19** [comment]
I've uploaded a new build which should fix your issue
https://www.curseforge.com/minecraft/mc-mods/ma-astral/files/2952460

**Comment by ShadoUchiha** [comment]
It fixed my issue. Thank you!
