### ISSUE TITLE
[1.15.2]Ethereal Tall Grass and other plants cannot be placed on the Ethereal Grass Block or Ethereal Dirt Block

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinerArcana/Astral#68]
I believe this is caused by Ethereal Grass Block and Ethereal Dirt Block not having Forge's dirt tag. Nothing too crazy but should be a simple fix to tack onto your next update. 

Otherwise, the blocks looks good! Nice work!

**Comment by drizzs** [comment]
Giving it the dirt tag would allow you to put down any plant. I think you'd have to account for the blocks existing even tho they're invisible you'd probably be able to place things down when they're not visible if you just tagged it. Just throwing that out there!

**Comment by Alan19** [comment]
Pushed a release that should fix the issue. Thanks!
https://www.curseforge.com/minecraft/mc-mods/ma-astral/files/2953243

**Comment by Alan19** [comment]
Does the new release fix the issue?

**Comment by TelepathicGrunt** [comment]
Yep! It fixes the issue. I'll close the issue report now.
