### ISSUE TITLE
Astral Travel limitations

### ISSUE THREAD

**Issue by Alan19** [MinerArcana/Astral#7]
Players with Astral Travel cannot:
- [x]  Interact with most blocks (tag controlled)
- [x]  Deal damage to non Astral mobs
- [x] Break non Astral blocks (can be controlled with tags).
- [x] Pick up most items (tag controlled)

**Comment by Divineaspect** [comment]
We probably also want to stop them from opening crafting table UIs

**Comment by FreneticScribbler** [comment]
It should be relatively trivial to allow astral players to open any gui but not interact with any of them, if that's what you want.

**Comment by Alan19** [comment]
That's what I would like
