### ISSUE TITLE
1.3.3 crashes dedicated server Forge 1.15.2 build 31.2.5

### ISSUE THREAD

**Issue by kreezxil** [MinerArcana/Astral#72]
Notes:
     looking for a class that doesn't' exist

crash report: 
http://paste.ubuntu.com/p/NbhZDXWyHx/

fml server latest: 
http://paste.ubuntu.com/p/WtFprvGBwP/

**Comment by Alan19** [comment]
Try this build:
https://www.curseforge.com/minecraft/mc-mods/ma-astral/files/2967893

**Comment by Alan19** [comment]
Does the new build fix the crash?

**Comment by kreezxil** [comment]
that one works, thank you.
