### ISSUE TITLE
The player can beat themselves to death in astral travel.

### ISSUE THREAD

**Issue by 00-Steven** [MinerArcana/Astral#75]
Astral Version: astral-1.4.2
Patchouli Version: Patchouli-1.15.2-1.2-34
Forge Version: 1.15.2-forge-31.2.8

The player can hit their own body while in astral travel, eventually leading to their own demise.

**Comment by Alan19** [comment]
I believe the damage is supposed to be 0 when that happens, but I'll see if I can remove the attack altogether.

**Comment by Alan19** [comment]
Closed by https://github.com/MinerArcana/Astral/commit/8eaaa1fd49efcc423d6f8d828810a8f1dab36a16
