### ISSUE TITLE
The hitbox of the comfortable cushion is misaligned.

### ISSUE THREAD

**Issue by 00-Steven** [MinerArcana/Astral#82]
Astral Version: astral-1.4.2
Patchouli Version: Patchouli-1.15.2-1.2-34
Forge Version: 1.15.2-forge-31.2.8

![2020-06-13_20 07 00](https://user-images.githubusercontent.com/42909981/84576035-ede13f00-adb1-11ea-9919-eb77efb5e402.png)

**Comment by Alan19** [comment]
Closed by https://github.com/MinerArcana/Astral/commit/76fc647699836cf3b7185e4a0bf518b78f7ebfbd
