### ISSUE TITLE
Astral versions 1.4.11 and 1.4.12 cause crash on launch with some mod(s)

### ISSUE THREAD

**Issue by Keltas** [MinerArcana/Astral#88]
To preface version 1.4.10 works fine, so the cause is probably some change in 1.4.11.  The game crashes on startup with some of my mods. I know the cause is not Pneumatic Craft mentioned in crash log, because removing it simply changes it to some other mod (occultism in this case). The crash log is below, together with latest log. I am using Forge 31.2.30 on Minecraft 1.15.2.
Crash:
https://paste.ubuntu.com/p/525JXVCWwz/
Latest:
https://paste.ubuntu.com/p/qnw6Hgy6zM/

**Comment by drizzs** [comment]
Hello, I was curious if Botania was present in your list of mods?

**Comment by Alan19** [comment]
Botania appears to be installed. I added Botania support in the newer versions but maybe I didn't handle the versions correctly.

**Comment by Alan19** [comment]
Is the modpack you're on a public modpack that I could download?

**Comment by Keltas** [comment]
Yes I have Botania. Unfortunately it is my private modpack and I don't know how to share it.

**Comment by Keltas** [comment]
I have removed Botania and can confirm that the game loads up properly without it (when on 1.4.12 version).

**Comment by Alan19** [comment]
I'm able to launch the game with only Botania and Astral and their dependencies. Can you check if that works for you and if so, can you see which other mod will cause the game to crash when those two are installed? I think one mod is changing how registries are loaded which is causing the crash.

**Comment by Keltas** [comment]
Ok after gradually removing all the mods until it stopped crashing I've found the combination of mods that causes the crash and yes it is quite a combination. Removing any one of them results in the crashing not occurring. Only all of them together crash as far as I can see (the latest log of crash https://pastebin.com/d88Pyb6k). I got all of these mods from Enigmatica 5 modpack, which you can download from Curseforge.
ftb-gui-library-1.0.0.14
tombstone-4.4.1-1.15.2
ftb-ranks-1.0.0.3
ftb-teams-1.0.0.5
ftb-chunks-1.1.0.12
corail_woodcutter-1.1.3-1.15.2
ftb-backups-2.1.0.1
corail_recycler-4.0.5-1.15.2
Plus Botania, Astral and their dependencies:
astral-1.4.12
curios-FORGE-1.15.2-2.0.2.4
Botania-r1.15-387
Patchouli-1.15.2-1.2-34

**Comment by Alan19** [comment]
I can't find either of the corail mods online

**Comment by Keltas** [comment]
They should be in mods folder after downloading Enigmatica 5. AFAIK they are not on Curseforge at the moment. They are external mods added to the pack.
Edit: Actually I can't find them anywhere either right now. The server files for Enigmatica have only Corail woodcutter.

**Comment by Keltas** [comment]
OK. Apparently Corail_31 mods are deleted due to some drama. I do have local copies of those mods, but from what I understood they are not coming back.

**Comment by Alan19** [comment]
Since the mod combination is no longer possible, if it okay if I close the issue until this occurs again with another combination of mods?

**Comment by Keltas** [comment]
Sure, go for it. No point in fixing bugs that no-one will encounter.

**Comment by Alan19** [comment]
Someone else had this issue. I don't know why DeferredRegister causes crashes with certain mod combinations, but switching to another form of registering may have fixed the issue.

https://www.curseforge.com/minecraft/mc-mods/ma-astral/files/3000084

**Comment by Alan19** [comment]
Feel free to close the issue if the issue gets fixed with the new version
