### ISSUE TITLE
Creative Player can still die while in Astral Form

### ISSUE THREAD

**Issue by WenXin20** [MinerArcana/Astral#91]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Astral v1.4.15`

If the player's body dies or takes damage, the player will die or take damage in creative mode.

**Comment by Alan19** [comment]
This is supposed to be intended behavior.

**Comment by WenXin20** [comment]
In creative?
And the medicine bowl is still consumed in creative.

**Comment by Alan19** [comment]
I believe potions and the like are still consumed in creative. I could change the body to not take damage if the player is in creative, but that will take time

**Comment by WenXin20** [comment]
Ok, thanks.
I meant to say that the medicine bowl is emptied when consumed in creative.
