### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by WenXin20** [MinerArcana/Astral#92]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Astral v1.4.15`

Astral leaves, logs, stripped logs, woods, planks, mushrooms, flowers, and saplings are missing their respective forge or Minecraft block and item tags, which would allow them to work in recipes.

Also, is Etheric Powder supposed to be placing buttons?

**Comment by Alan19** [comment]
The button is a placeholder texture. It'll be replaced with a more mystical design sometime in the future.

**Comment by Alan19** [comment]
I added the tags. That fixed the issue with the leaves as well. :)

**Comment by WenXin20** [comment]
Thanks! I just took a look at the commit, is the Stripped Ethereal Wood block being in the planks tag instead of the logs tag intentional? And the normal Ethereal Log might've been missed.

**Comment by Alan19** [comment]
I think it's set up correctly, but I might have the naming conventions wrong for the blocks

**Comment by Alan19** [comment]
And I think stripped planks don't exist after checking the minecraft wiki

**Comment by Alan19** [comment]
Oh, I see what I did wrong. Stripped wood is not considered a plank.

**Comment by Alan19** [comment]
And I'm missing Ethereal Wood
