### ISSUE TITLE
Saplings grow with only 2 logs

### ISSUE THREAD

**Issue by WenXin20** [MinerArcana/Astral#93]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Astral v1.4.15`

When the astral sapling is grown, only one or two logs are spawned at the bottom, the rest are leaves.

**Comment by Alan19** [comment]
I'll bump the height a bit higher and see if that helps

**Comment by WenXin20** [comment]
Oh sorry, the height is fine. I meant that the logs don't go through the leaves the way it does with oak trees. I'll get a screenshot to clarify.

**Comment by WenXin20** [comment]
Here is what I meant:
![2020-07-21_19 13 24](https://user-images.githubusercontent.com/12000593/88119732-ea965b80-cb86-11ea-8e1f-3fcb0df12d29.png)
